sudo: required
services:
  - docker

before_install:
  - docker build -t hwdavr/nodejs_server_app_template -f Dockerfile .

script:
  - docker run -e CI=true hwdavr/nodejs_server_app_template npm run test 

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-west-2-306476627547"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
